
(()=>{const KEY="blueChampionshipScoutV1";let data=load(),latest=null,watchId=null,activeRoute=null;const $=id=>document.getElementById(id),now=()=>new Date().toISOString();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{points:[],routes:[]}}catch(_){return{points:[],routes:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function request(cb){if(!navigator.geolocation)return alert("Geolocation is not available.");$("gpsMessage").textContent="Checking location…";navigator.geolocation.getCurrentPosition(pos=>{latest={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,altitude:pos.coords.altitude,timestamp:new Date(pos.timestamp).toISOString()};$("lat").textContent=latest.lat.toFixed(7);$("lng").textContent=latest.lng.toFixed(7);$("accuracy").textContent=Math.round(latest.accuracy)+" m";$("gpsMessage").textContent=latest.accuracy<=10?"Good reading. Save the point while standing still.":"Accuracy is broad. Wait in an open area and try again before saving a critical point.";if(cb)cb(latest)},err=>$("gpsMessage").textContent="GPS error: "+err.message,{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
$("gpsBtn").onclick=()=>request();
$("savePoint").onclick=()=>{const name=$("pointName").value.trim();if(!name)return alert("Add a useful point name.");request(p=>{data.points.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:$("pointType").value,name,notes:$("pointNotes").value.trim(),...p,createdAt:now()});save();$("pointName").value="";$("pointNotes").value="";alert("Point saved.")})};
$("startRoute").onclick=()=>{const name=$("routeName").value.trim();if(!name)return alert("Name the route before recording it.");if(!navigator.geolocation)return alert("Geolocation is not available.");activeRoute={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,status:$("routeStatus").value,notes:$("routeNotes").value.trim(),startedAt:now(),points:[]};$("routePanel").classList.add("recording");$("startRoute").classList.add("hidden");$("stopRoute").classList.remove("hidden");$("routeStatusText").textContent="Recording. Walk the cart path with this page open.";watchId=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,timestamp:new Date(pos.timestamp).toISOString()},last=activeRoute.points[activeRoute.points.length-1];if(!last||(new Date(p.timestamp)-new Date(last.timestamp)>=3000))activeRoute.points.push(p);$("routeStatusText").textContent=`Recording: ${activeRoute.points.length} GPS points; current accuracy ${Math.round(p.accuracy)} m.`},err=>$("routeStatusText").textContent="Route GPS error: "+err.message,{enableHighAccuracy:true,maximumAge:0,timeout:20000})};
$("stopRoute").onclick=()=>{if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;if(activeRoute&&activeRoute.points.length>=2){activeRoute.endedAt=now();data.routes.push(activeRoute);save();alert(`Route saved with ${activeRoute.points.length} GPS points.`)}else alert("Not enough GPS points were collected.");activeRoute=null;$("routePanel").classList.remove("recording");$("startRoute").classList.remove("hidden");$("stopRoute").classList.add("hidden");$("routeStatusText").textContent="";$("routeName").value="";$("routeNotes").value=""};
function blob(){return new Blob([JSON.stringify({...data,exportedAt:now()},null,2)],{type:"application/json"})}function fname(){return`blue-championship-scout-${new Date().toISOString().slice(0,10)}.json`}
$("downloadJson").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob());a.download=fname();a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("copyJson").onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify({...data,exportedAt:now()},null,2));alert("Scouting data copied.")};
$("shareJson").onclick=async()=>{const f=new File([blob()],fname(),{type:"application/json"});if(navigator.canShare&&navigator.canShare({files:[f]}))await navigator.share({title:"Course scouting data",files:[f]});else alert("File sharing is not supported here. Use Download instead.")};
$("clearAll").onclick=()=>{if(confirm("Delete every saved point and route from this phone?")){data={points:[],routes:[]};save()}};
function render(){const r=$("savedList");r.innerHTML=`<p><strong>${data.points.length}</strong> points · <strong>${data.routes.length}</strong> routes</p>`;data.points.slice().reverse().forEach(p=>{const e=document.createElement("div");e.className="item";e.innerHTML=`<strong>${esc(p.name)}</strong><br><span class="small">${esc(p.type)} · ${p.lat.toFixed(6)}, ${p.lng.toFixed(6)} · accuracy ${Math.round(p.accuracy)} m</span>`;r.appendChild(e)});data.routes.slice().reverse().forEach(x=>{const e=document.createElement("div");e.className="item";e.innerHTML=`<strong>${esc(x.name)}</strong><br><span class="small">${esc(x.status)} · ${x.points.length} GPS points</span>`;r.appendChild(e)})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}render()})();
